name: stressed_unicorn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  syncfusion_flutter_charts: ^28.2.7
  intl: ^0.20.2
  file_picker: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.25.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
